apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: stm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: henryggg/stm-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: stm_db
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
