apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: stm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: henryggg/stm-frontend:k8s-stable
          imagePullPolicy: Always
          ports:
            - containerPort: 80